from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal
from pathlib import Path

import xlsxwriter
from PIL import Image

from .models import calculate_price_statistics
from .resources import resource_path

EXCEL_CHART_MAX_WIDTH = 680
EXCEL_CHART_MAX_HEIGHT = 300


def fit_image_within(
    image_width: int,
    image_height: int,
    max_width: int,
    max_height: int,
) -> tuple[int, int]:
    """Fit an image inside a box without changing its aspect ratio."""
    if min(image_width, image_height, max_width, max_height) <= 0:
        raise ValueError("Image and bounding-box dimensions must be positive.")
    scale = min(max_width / image_width, max_height / image_height, 1.0)
    return max(1, round(image_width * scale)), max(1, round(image_height * scale))


def export_price_history_xlsx(
    output_path: str | Path,
    rows: Sequence[object],
    *,
    exported_at: datetime | None = None,
    chart_image_path: str | Path | None = None,
) -> Path:
    if not rows:
        raise ValueError("There are no saved price checks to export.")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    exported_at = exported_at or datetime.now().astimezone()
    prices = [Decimal(row["unit_price"]) for row in rows]
    statistics = calculate_price_statistics(prices)
    last = rows[-1]
    currency = str(last["currency"]).replace('"', '""')
    last_data_row = len(rows) + 1

    # Values such as seller and listing names originate outside the app. Keep
    # leading '=' characters as text so an exported workbook cannot turn them
    # into formulas when opened in Excel. Application formulas are still added
    # explicitly with write_formula() below.
    workbook = xlsxwriter.Workbook(
        output,
        {
            "strings_to_formulas": False,
            "strings_to_urls": False,
        },
    )
    workbook.set_properties(
        {
            "title": "G2G Price Tracker export",
            "subject": "Saved seller and market price history",
            "author": "kuti-code",
            "comments": "Generated by G2G Price Tracker",
        }
    )
    summary = workbook.add_worksheet("Summary")
    checks = workbook.add_worksheet("Price Checks")
    summary.hide_gridlines(2)
    checks.hide_gridlines(2)

    title_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 18,
            "font_color": "#FFFFFF",
            "bg_color": "#0F766E",
            "align": "left",
            "valign": "vcenter",
            # Leave a compact gap for the 32 px logo anchored at A1.
            "indent": 5,
        }
    )
    section_format = workbook.add_format(
        {
            "bold": True,
            "font_color": "#18212F",
            "bg_color": "#E8EDF2",
            "bottom": 1,
            "bottom_color": "#D0D5DD",
        }
    )
    label_format = workbook.add_format({"bold": True, "font_color": "#667085"})
    centered_label_format = workbook.add_format(
        {"bold": True, "font_color": "#667085", "align": "center", "valign": "vcenter"}
    )
    text_format = workbook.add_format({"font_color": "#18212F"})
    centered_text_format = workbook.add_format(
        {"font_color": "#18212F", "align": "center", "valign": "vcenter"}
    )
    link_format = workbook.add_format({"font_color": "#0F766E", "underline": True, "align": "left"})
    price_format = workbook.add_format(
        {"num_format": f'0.000000 "{currency}"', "font_color": "#18212F"}
    )
    centered_price_format = workbook.add_format(
        {
            "num_format": f'0.000000 "{currency}"',
            "font_color": "#18212F",
            "align": "center",
        }
    )
    date_format = workbook.add_format(
        {"num_format": "yyyy-mm-dd hh:mm:ss", "font_color": "#18212F", "align": "left"}
    )
    header_format = workbook.add_format(
        {
            "bold": True,
            "font_color": "#FFFFFF",
            "bg_color": "#0F766E",
            "align": "center",
            "valign": "vcenter",
            "bottom": 1,
            "bottom_color": "#0B5D57",
        }
    )
    integer_format = workbook.add_format({"num_format": "0"})
    centered_integer_format = workbook.add_format({"num_format": "0", "align": "center"})
    footer_format = workbook.add_format({"italic": True, "font_color": "#667085", "align": "left"})

    summary.set_row(0, 32)
    summary.merge_range("A1:N1", "G2G Price Tracker — Data Export", title_format)
    summary.set_column("A:D", 22)
    summary.set_column("E:E", 3)
    summary.set_column("F:N", 12)
    summary.set_landscape()
    summary.fit_to_pages(1, 1)
    summary.print_area("A1:N20")
    summary.set_margins(0.35, 0.35, 0.45, 0.45)
    summary.write("A3", "Target", section_format)
    summary.write("A4", "Seller", label_format)
    summary.write("B4", last["seller"], text_format)
    summary.write("A5", "Listing", label_format)
    summary.merge_range("B5:D5", last["listing_title"], text_format)
    summary.write("A6", "Category", label_format)
    summary.write("B6", last["category"], text_format)
    summary.write("A7", "Currency", label_format)
    summary.write("B7", last["currency"], text_format)
    summary.write("A8", "Exported at", label_format)
    summary.write_datetime("B8", exported_at.replace(tzinfo=None), date_format)
    summary.write("A9", "Source URL", label_format)
    summary.write_url("B9", last["source_url"], link_format, "Open G2G source")

    summary.merge_range("A11:D11", "Price Summary", section_format)
    summary.write_row(
        "A12",
        ["Seller Latest Price", "Seller Lowest", "Seller Highest", "Price Checks"],
        centered_label_format,
    )
    summary.write_formula(
        "A13",
        f"=INDEX('Price Checks'!$E$2:$E${last_data_row},ROWS('Price Checks'!$E$2:$E${last_data_row}))",
        centered_price_format,
        float(statistics.latest),
    )
    summary.write_formula(
        "B13",
        f"=MIN('Price Checks'!$E$2:$E${last_data_row})",
        centered_price_format,
        float(statistics.lowest),
    )
    summary.write_formula(
        "C13",
        f"=MAX('Price Checks'!$E$2:$E${last_data_row})",
        centered_price_format,
        float(statistics.highest),
    )
    summary.write_formula(
        "D13",
        f"=COUNTA('Price Checks'!$A$2:$A${last_data_row})",
        centered_integer_format,
        len(rows),
    )
    summary.write_row(
        "A15",
        [
            "Seller Average",
            "Market Average (Lowest 5)",
            "Market Lowest",
            "Market Lowest Seller",
        ],
        centered_label_format,
    )
    summary.write_formula(
        "A16",
        f"=AVERAGE('Price Checks'!$E$2:$E${last_data_row})",
        centered_price_format,
        float(statistics.all_time_average),
    )
    latest_market_average = last["market_average_price"]
    if latest_market_average is not None:
        summary.write_formula(
            "B16",
            f"=INDEX('Price Checks'!$K$2:$K${last_data_row},ROWS('Price Checks'!$K$2:$K${last_data_row}))",
            centered_price_format,
            float(Decimal(latest_market_average)),
        )
    else:
        summary.write_blank("B16", None, centered_price_format)
    latest_market_price = last["market_lowest_price"]
    if latest_market_price is not None:
        summary.write_formula(
            "C16",
            f"=INDEX('Price Checks'!$I$2:$I${last_data_row},ROWS('Price Checks'!$I$2:$I${last_data_row}))",
            centered_price_format,
            float(Decimal(latest_market_price)),
        )
    else:
        summary.write_blank("C16", None, centered_price_format)
    summary.write("D16", last["market_lowest_seller"] or "—", centered_text_format)
    summary.merge_range("A19:D19", "by: kuti-code", footer_format)

    image = Path(chart_image_path) if chart_image_path else None
    if image and image.is_file():
        with Image.open(image) as chart_image:
            image_width, image_height = chart_image.size
        display_width, display_height = fit_image_within(
            image_width,
            image_height,
            EXCEL_CHART_MAX_WIDTH,
            EXCEL_CHART_MAX_HEIGHT,
        )
        image_scale = min(display_width / image_width, display_height / image_height)
        summary.insert_image(
            "F3",
            str(image),
            {
                "x_scale": image_scale,
                "y_scale": image_scale,
                "x_offset": 4,
                "y_offset": 4,
                "object_position": 1,
            },
        )

    logo = resource_path("assets", "g2g-price-tracker.png")
    if logo.is_file():
        with Image.open(logo) as logo_image:
            logo_width, logo_height = logo_image.size
        summary.insert_image(
            "A1",
            str(logo),
            {
                "x_scale": 32 / logo_width,
                "y_scale": 32 / logo_height,
                "x_offset": 6,
                "y_offset": 5,
                "object_position": 1,
                "description": "G2G Price Tracker logo",
            },
        )

    headers = [
        "ID",
        "Seller",
        "Listing Title",
        "Category",
        "Seller Price",
        "Currency",
        "Source URL",
        "Checked At",
        "Market Lowest Price",
        "Market Lowest Seller",
        "Market Average (Lowest 5)",
    ]
    checks.write_row(0, 0, headers, header_format)
    for row_index, row in enumerate(rows, start=1):
        observed_at = datetime.fromisoformat(row["observed_at"]).astimezone().replace(tzinfo=None)
        checks.write_number(row_index, 0, int(row["id"]), integer_format)
        checks.write_string(row_index, 1, row["seller"], text_format)
        checks.write_string(row_index, 2, row["listing_title"], text_format)
        checks.write_string(row_index, 3, row["category"], text_format)
        checks.write_number(row_index, 4, float(Decimal(row["unit_price"])), price_format)
        checks.write_string(row_index, 5, row["currency"], text_format)
        checks.write_url(row_index, 6, row["source_url"], link_format, "Open G2G source")
        checks.write_datetime(row_index, 7, observed_at, date_format)
        if row["market_lowest_price"] is not None:
            checks.write_number(
                row_index, 8, float(Decimal(row["market_lowest_price"])), price_format
            )
        checks.write_string(row_index, 9, row["market_lowest_seller"] or "", text_format)
        if row["market_average_price"] is not None:
            checks.write_number(
                row_index, 10, float(Decimal(row["market_average_price"])), price_format
            )

    widths = {
        "A:A": 9,
        "B:B": 20,
        "C:C": 45,
        "D:D": 24,
        "E:E": 15,
        "F:F": 10,
        "G:G": 21,
        "H:H": 21,
        "I:I": 20,
        "J:J": 22,
        "K:K": 23,
    }
    for columns, width in widths.items():
        checks.set_column(columns, width)
    checks.set_row(0, 24)
    checks.freeze_panes(1, 0)
    checks.autofilter(0, 0, len(rows), len(headers) - 1)
    checks.set_landscape()
    checks.fit_to_pages(1, 0)
    checks.repeat_rows(0)
    checks.set_margins(0.3, 0.3, 0.45, 0.45)

    workbook.close()
    return output
